.Dd August 23, 2019
.Dt NOPEN 1
.Os
.Sh NAME
.Nm nopen
.Nd opens a file in the user's preferred application
.Sh SYNOPSIS
.Nm
.Ar file...
.Sh DESCRIPTION
.Nm
opens the files provided as arguments with the user's preferred
application.
.Pp
The file associations are specified by regexes
matching on the currently selected filename.
If a match is found the associated program is executed
with the file passed in as the argument.
If no match is found the program
.Xr less 1
is invoked on the given file.
.Sh CONFIGURATION
.Nm
is configured by modifying
.Pa nopenconf.h
and recompiling the code.
.Sh SEE ALSO
.Xr noice 1
.Sh AUTHORS
.An Lazaros Koromilas Aq Mt lostd@2f30.org ,
.An Dimitris Papastamos Aq Mt sin@2f30.org .
